/**
 * Types and static reference metadata for the Planning Engine — a
 * pre-writing pipeline: an **intake conversation** first (the writer
 * describes the book in plain language, a link, or an attached document),
 * then Stage 1 Core Summary -> Stage 2 Act Outlines -> Stage 3 Chapter
 * Beats, each stage generated by an agent, reviewed by two parallel
 * Critics, synthesized by an Arbitrator, and gated on explicit human
 * approval before advancing. This never writes manuscript prose — that's
 * still exclusively the Generate/Hanami flow; this is the pre-writing/
 * planning phase, backed by the real backend's `agent_prompts` and
 * `planning_runs` tables (see the backend repo's
 * `src/routes/agentPrompts.ts` / `src/routes/planning.ts` and
 * `src/services/planningEngine.ts`).
 *
 * Every agent's behavior comes from a database row someone authors and
 * saves through the Prompt Editor — the backend contains zero prompt
 * content of its own. Every prompt this app's book currently has active
 * was written by an AI session getting the pipeline working end-to-end,
 * not the writer — see `AgentPromptAuthor` below for how the editor
 * surfaces that distinction.
 */

export type AgentRole =
  | "generator"
  | "logic_critic"
  | "suspense_critic"
  | "arbitrator_panel"
  | "arbitrator_chat"
  | "arbitrator_directive"
  | "entity_extractor";

export const AGENT_ROLES: AgentRole[] = [
  "generator",
  "logic_critic",
  "suspense_critic",
  "arbitrator_panel",
  "arbitrator_chat",
  "arbitrator_directive",
  "entity_extractor",
];

export const AGENT_ROLE_META: Record<AgentRole, { label: string; description: string }> = {
  generator: {
    label: "Generator",
    description: "Writes each stage's artifact — the Core Summary, Act Outlines, or Chapter Beats.",
  },
  logic_critic: {
    label: "Logic Critic",
    description: "Reviews the artifact for plot-logic and consistency problems.",
  },
  suspense_critic: {
    label: "Suspense Critic",
    description: "Reviews the artifact for pacing, tension, and hook strength.",
  },
  arbitrator_panel: {
    label: "Arbitrator — Panel Synthesis",
    description: "Synthesizes both critics' reviews into one verdict for the human review gate.",
  },
  arbitrator_chat: {
    label: "Arbitrator — Chat",
    description: "Runs the interview after an artifact is rejected at the review gate.",
  },
  arbitrator_directive: {
    label: "Arbitrator — Directive",
    description: "Compiles the rejection interview into a delta directive for the next regeneration.",
  },
  entity_extractor: {
    label: "Entity Extractor",
    description: "Pulls new characters and world elements out of the approved Chapter Beats.",
  },
};

/**
 * `entity_extractor` is the one role that genuinely only ever needs a
 * single "all" version — the backend looks it up hardcoded at stage
 * `"all"` (see `extractEntities()` in the backend's `planningEngine.ts`),
 * never at a run's actual `current_stage`. A UI hint, not an enforced
 * rule elsewhere: "all" is always a valid stage for any role.
 */
export const SINGLE_STAGE_ROLES = new Set<AgentRole>(["entity_extractor"]);

/**
 * `arbitrator_chat` and `arbitrator_directive` are looked up at TWO
 * distinct stages depending on the moment: `"intake"` for the pre-Stage-1
 * conversation, and the run's real current stage (falling back to
 * `"all"`) for a mid-pipeline rejection interview — confirmed by reading
 * `intakeChatTurn()`/`finalizeIntake()` vs. `chatTurn()`/`finalizeDirective()`
 * in the backend directly. Each moment gets different placeholders (see
 * `placeholdersFor()` below), so these two roles need their own version
 * at `"intake"` AND one at `"all"` (or a specific stage) to work for both.
 */
export const DUAL_MOMENT_ROLES = new Set<AgentRole>(["arbitrator_chat", "arbitrator_directive"]);

export type PlanningStage = "stage_1_summary" | "stage_2_acts" | "stage_3_beats" | "intake" | "all";

export const PLANNING_STAGES: PlanningStage[] = ["stage_1_summary", "stage_2_acts", "stage_3_beats", "intake", "all"];

/** The three real pipeline stages, in order — a run's `current_stage` is never "all" or "intake"; those only exist as prompt-lookup stages. */
export const RUN_STAGES: Exclude<PlanningStage, "all" | "intake">[] = ["stage_1_summary", "stage_2_acts", "stage_3_beats"];

export const PLANNING_STAGE_META: Record<PlanningStage, { label: string; short: string }> = {
  stage_1_summary: { label: "Stage 1 — Core Summary", short: "Summary" },
  stage_2_acts: { label: "Stage 2 — Act Outlines", short: "Acts" },
  stage_3_beats: { label: "Stage 3 — Chapter Beats", short: "Beats" },
  intake: { label: "Intake (pre-Stage 1)", short: "Intake" },
  all: { label: "All Stages", short: "All" },
};

export const EFFORT_LEVELS = ["low", "medium", "high", "xhigh", "max"] as const;
export type EffortLevel = (typeof EFFORT_LEVELS)[number];

export const DEFAULT_MODEL = "claude-sonnet-5";
export const DEFAULT_EFFORT: EffortLevel = "high";

/**
 * Who wrote this version — `"claude"` for the prompts an AI session
 * seeded to get this book's pipeline working, `"writer"` for anything
 * the actual writer has authored or edited themselves. Not enforced by
 * any type on the backend's own side (its `agent_prompts` row shape
 * doesn't declare this field in TypeScript), but the column is real —
 * `GET /agent-prompts` returns it via a plain `select("*")`, and it's
 * absent-safe here (`mapPromptRow` falls back to `"writer"`) in case a
 * row genuinely doesn't have it set.
 */
export type AgentPromptAuthor = "writer" | "claude";

/** One authored version of one agent's behavior at one stage — every field is writer-owned, nothing here is generated. */
export type AgentPrompt = {
  id: string;
  bookId: string;
  agentRole: AgentRole;
  stage: PlanningStage;
  version: number;
  isActive: boolean;
  systemPrompt: string;
  userPromptTemplate: string;
  model: string;
  effort: EffortLevel;
  authoredBy: AgentPromptAuthor;
  createdAt: string;
};

export type PlanningRunStatus =
  | "intake_active"
  | "generating"
  | "critiquing"
  | "awaiting_arbitration"
  | "awaiting_user_review"
  | "user_chat_active"
  | "awaiting_entity_review"
  | "done"
  | "failed";

export const PLANNING_RUN_STATUS_LABEL: Record<PlanningRunStatus, string> = {
  intake_active: "Describing your book",
  generating: "Generating",
  critiquing: "Running critique",
  awaiting_arbitration: "Arbitrating",
  awaiting_user_review: "Awaiting your review",
  user_chat_active: "Rejection interview",
  awaiting_entity_review: "Reviewing extracted entities",
  done: "Done",
  failed: "Failed",
};

export type PlanningChatMessage = { role: "user" | "assistant"; content: string };

export type ExtractedEntityCandidate = {
  type: "codex_entry" | "world_category";
  name: string;
  entryType?: string;
  description?: string;
};

export type PlanningRun = {
  id: string;
  bookId: string;
  userId: string;
  currentStage: Exclude<PlanningStage, "all" | "intake">;
  status: PlanningRunStatus;
  stageArtifacts: Partial<Record<Exclude<PlanningStage, "all" | "intake">, string>>;
  panelReviews: { logic_critic?: unknown; suspense_critic?: unknown } | null;
  arbitratorSynthesis: unknown;
  /** Mid-pipeline rejection interviews — a separate thread from intakeChatHistory. */
  chatHistory: PlanningChatMessage[];
  /** The one-time pre-Stage-1 conversation (status "intake_active") where the writer describes the book. */
  intakeChatHistory: PlanningChatMessage[];
  finalDeltaDirective: string | null;
  extractedEntities: ExtractedEntityCandidate[] | null;
  lastError: string | null;
  createdAt: string;
  updatedAt: string;
};

/**
 * Which `{{PLACEHOLDER}}` tokens a role's user_prompt_template can
 * reference — shown next to the template field in the Prompt Editor.
 * Anything not present in a given call is just left blank server-side,
 * no error, so this is documentation, not validation.
 *
 * A function, not a flat per-role table, because `arbitrator_chat` and
 * `arbitrator_directive` genuinely receive different placeholders
 * depending on *which* moment their prompt is being looked up for —
 * confirmed by reading `intakeChatTurn()`/`finalizeIntake()` (stage
 * `"intake"`) vs. `chatTurn()`/`finalizeDirective()` (any other stage)
 * directly in the backend's `planningEngine.ts`, rather than trusting a
 * single static table. `entity_extractor` also actually receives
 * `{{CURRENT_ARTIFACT}}` (the approved Stage 3 Beats JSON) even though
 * an earlier version of the feature spec omitted it — confirmed the same
 * way, via `extractEntities()`.
 */
export function placeholdersFor(role: AgentRole, stage: PlanningStage): { token: string; meaning: string }[] {
  switch (role) {
    case "generator":
      return [
        { token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" },
        { token: "{{PRIOR_STAGE_ARTIFACT}}", meaning: "The previous stage's approved text (blank at Stage 1)" },
        { token: "{{FINAL_DELTA_DIRECTIVE}}", meaning: "Set after intake, or after a rejection's finalize-directive" },
      ];
    case "logic_critic":
    case "suspense_critic":
      return [
        { token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" },
        { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact currently being reviewed" },
      ];
    case "arbitrator_panel":
      return [
        { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact currently being reviewed" },
        { token: "{{PANEL_REVIEWS}}", meaning: "Both critics' JSON output" },
      ];
    case "arbitrator_chat":
      return stage === "intake"
        ? [
            {
              token: "{{BOOK_CONTEXT}}",
              meaning: "Book Facts + Codex JSON — keeps intake aware of an already-established book",
            },
          ]
        : [
            { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact being reconsidered after rejection" },
            { token: "{{PANEL_REVIEWS}}", meaning: "Both critics' JSON output" },
          ];
    case "arbitrator_directive":
      return stage === "intake"
        ? [{ token: "{{CHAT_HISTORY}}", meaning: "The full intake conversation" }]
        : [
            { token: "{{CHAT_HISTORY}}", meaning: "The full rejection interview" },
            { token: "{{PANEL_REVIEWS}}", meaning: "Both critics' JSON output" },
            { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact being reconsidered" },
          ];
    case "entity_extractor":
      return [
        { token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" },
        { token: "{{CURRENT_ARTIFACT}}", meaning: "The approved Stage 3 Chapter Beats JSON to extract entities from" },
      ];
  }
}

/** A short note on which stage(s) a role is actually looked up at, for the roles where that isn't just "whatever you pick." */
export function roleStageGuidance(role: AgentRole): string | null {
  if (SINGLE_STAGE_ROLES.has(role)) {
    return 'Always looked up at stage "All Stages" — save your version there.';
  }
  if (DUAL_MOMENT_ROLES.has(role)) {
    return 'Looked up separately for two different moments: "Intake" for the pre-Stage-1 conversation, and the run\'s current stage (falling back to "All Stages") for a rejection interview. Save a version at each if you want them to sound different.';
  }
  return null;
}

/**
 * Two role/stage combinations get parsed by code, not just displayed —
 * getting the shape wrong means a clean, specific error rather than a
 * crash, but still worth a visible hint in the editor.
 */
export function outputShapeHint(role: AgentRole, stage: PlanningStage): string | null {
  if (role === "generator" && stage === "stage_3_beats") {
    return 'Must return JSON:\n{"chapters": [{"chapterNumber": 1, "title": "...", "beats": [{"title": "...", "outlineText": "..."}]}]}';
  }
  if (role === "entity_extractor") {
    return 'Must return a JSON array:\n[{"type": "codex_entry" | "world_category", "name": "...", "entryType": "...", "description": "..."}]';
  }
  return null;
}
