/**
 * Types and static reference metadata for the Planning Engine — a
 * pre-writing pipeline (Stage 1 Core Summary -> Stage 2 Act Outlines ->
 * Stage 3 Chapter Beats), each stage generated by an agent, reviewed by
 * two parallel Critics, synthesized by an Arbitrator, and gated on
 * explicit human approval before advancing. This never writes manuscript
 * prose — that's still exclusively the Generate/Hanami flow; this is the
 * pre-writing/planning phase, backed by the real backend's
 * `agent_prompts` and `planning_runs` tables (see the backend repo's
 * `src/routes/agentPrompts.ts` / `src/routes/planning.ts` and
 * `src/services/planningEngine.ts`).
 *
 * Every agent's behavior comes from a database row the writer authors and
 * saves through the Prompt Editor — the backend contains zero prompt
 * content of its own, so a run has nothing to do until at least the four
 * Stage 1 prompts exist.
 */

export type AgentRole =
  | "generator"
  | "logic_critic"
  | "suspense_critic"
  | "arbitrator_panel"
  | "arbitrator_chat"
  | "arbitrator_directive"
  | "entity_extractor";

export const AGENT_ROLES: AgentRole[] = [
  "generator",
  "logic_critic",
  "suspense_critic",
  "arbitrator_panel",
  "arbitrator_chat",
  "arbitrator_directive",
  "entity_extractor",
];

export const AGENT_ROLE_META: Record<AgentRole, { label: string; description: string }> = {
  generator: {
    label: "Generator",
    description: "Writes each stage's artifact — the Core Summary, Act Outlines, or Chapter Beats.",
  },
  logic_critic: {
    label: "Logic Critic",
    description: "Reviews the artifact for plot-logic and consistency problems.",
  },
  suspense_critic: {
    label: "Suspense Critic",
    description: "Reviews the artifact for pacing, tension, and hook strength.",
  },
  arbitrator_panel: {
    label: "Arbitrator — Panel Synthesis",
    description: "Synthesizes both critics' reviews into one verdict for the human review gate.",
  },
  arbitrator_chat: {
    label: "Arbitrator — Chat",
    description: "Runs the interview after an artifact is rejected at the review gate.",
  },
  arbitrator_directive: {
    label: "Arbitrator — Directive",
    description: "Compiles the rejection interview into a delta directive for the next regeneration.",
  },
  entity_extractor: {
    label: "Entity Extractor",
    description: "Pulls new characters and world elements out of the approved Chapter Beats.",
  },
};

/**
 * These three roles typically only need one prompt version, ever, since
 * their job doesn't change per stage — a UI hint, not an enforced rule:
 * "all" is always a valid stage for any role.
 */
export const SINGLE_STAGE_ROLES = new Set<AgentRole>(["arbitrator_chat", "arbitrator_directive", "entity_extractor"]);

export type PlanningStage = "stage_1_summary" | "stage_2_acts" | "stage_3_beats" | "all";

export const PLANNING_STAGES: PlanningStage[] = ["stage_1_summary", "stage_2_acts", "stage_3_beats", "all"];

/** The three real pipeline stages, in order — "all" isn't a stage a run is ever actually at, only a prompt-authoring convenience. */
export const RUN_STAGES: Exclude<PlanningStage, "all">[] = ["stage_1_summary", "stage_2_acts", "stage_3_beats"];

export const PLANNING_STAGE_META: Record<PlanningStage, { label: string; short: string }> = {
  stage_1_summary: { label: "Stage 1 — Core Summary", short: "Summary" },
  stage_2_acts: { label: "Stage 2 — Act Outlines", short: "Acts" },
  stage_3_beats: { label: "Stage 3 — Chapter Beats", short: "Beats" },
  all: { label: "All Stages", short: "All" },
};

export const EFFORT_LEVELS = ["low", "medium", "high", "xhigh", "max"] as const;
export type EffortLevel = (typeof EFFORT_LEVELS)[number];

export const DEFAULT_MODEL = "claude-sonnet-5";
export const DEFAULT_EFFORT: EffortLevel = "high";

/** One authored version of one agent's behavior at one stage — every field is writer-owned, nothing here is generated. */
export type AgentPrompt = {
  id: string;
  bookId: string;
  agentRole: AgentRole;
  stage: PlanningStage;
  version: number;
  isActive: boolean;
  systemPrompt: string;
  userPromptTemplate: string;
  model: string;
  effort: EffortLevel;
  createdAt: string;
};

export type PlanningRunStatus =
  | "generating"
  | "critiquing"
  | "awaiting_arbitration"
  | "awaiting_user_review"
  | "user_chat_active"
  | "awaiting_entity_review"
  | "done"
  | "failed";

export const PLANNING_RUN_STATUS_LABEL: Record<PlanningRunStatus, string> = {
  generating: "Generating",
  critiquing: "Running critique",
  awaiting_arbitration: "Arbitrating",
  awaiting_user_review: "Awaiting your review",
  user_chat_active: "Rejection interview",
  awaiting_entity_review: "Reviewing extracted entities",
  done: "Done",
  failed: "Failed",
};

export type PlanningChatMessage = { role: "user" | "assistant"; content: string };

export type ExtractedEntityCandidate = {
  type: "codex_entry" | "world_category";
  name: string;
  entryType?: string;
  description?: string;
};

export type PlanningRun = {
  id: string;
  bookId: string;
  userId: string;
  currentStage: Exclude<PlanningStage, "all">;
  status: PlanningRunStatus;
  stageArtifacts: Partial<Record<Exclude<PlanningStage, "all">, string>>;
  panelReviews: { logic_critic?: unknown; suspense_critic?: unknown } | null;
  arbitratorSynthesis: unknown;
  chatHistory: PlanningChatMessage[];
  finalDeltaDirective: string | null;
  extractedEntities: ExtractedEntityCandidate[] | null;
  lastError: string | null;
  createdAt: string;
  updatedAt: string;
};

/**
 * Which `{{PLACEHOLDER}}` tokens a role's user_prompt_template can
 * reference — shown next to the template field in the Prompt Editor.
 * Anything not present in a given call is just left blank server-side,
 * no error, so this is documentation, not validation.
 */
export const PLACEHOLDER_REFERENCE: Record<AgentRole, { token: string; meaning: string }[]> = {
  generator: [
    { token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" },
    { token: "{{PRIOR_STAGE_ARTIFACT}}", meaning: "The previous stage's approved text" },
    { token: "{{FINAL_DELTA_DIRECTIVE}}", meaning: "Set only when regenerating after a rejection" },
  ],
  logic_critic: [
    { token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" },
    { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact currently being reviewed" },
  ],
  suspense_critic: [
    { token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" },
    { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact currently being reviewed" },
  ],
  arbitrator_panel: [
    { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact currently being reviewed" },
    { token: "{{PANEL_REVIEWS}}", meaning: "Both critics' JSON output" },
  ],
  arbitrator_chat: [
    { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact currently being reviewed" },
    { token: "{{PANEL_REVIEWS}}", meaning: "Both critics' JSON output" },
  ],
  arbitrator_directive: [
    { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact currently being reviewed" },
    { token: "{{PANEL_REVIEWS}}", meaning: "Both critics' JSON output" },
    { token: "{{CHAT_HISTORY}}", meaning: "The full rejection interview" },
  ],
  entity_extractor: [{ token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" }],
};

/**
 * Two role/stage combinations get parsed by code, not just displayed —
 * getting the shape wrong means a clean, specific error rather than a
 * crash, but still worth a visible hint in the editor.
 */
export function outputShapeHint(role: AgentRole, stage: PlanningStage): string | null {
  if (role === "generator" && stage === "stage_3_beats") {
    return 'Must return JSON:\n{"chapters": [{"chapterNumber": 1, "title": "...", "beats": [{"title": "...", "outlineText": "..."}]}]}';
  }
  if (role === "entity_extractor") {
    return 'Must return a JSON array:\n[{"type": "codex_entry" | "world_category", "name": "...", "entryType": "...", "description": "..."}]';
  }
  return null;
}
