/**
 * Types and static reference metadata for the Planning Engine — a
 * pre-writing pipeline: an **intake conversation** first (the writer
 * describes the book in plain language, a link, or an attached document),
 * then Stage 1 Core Summary -> Stage 2 Act Outlines -> Stage 3 Chapter
 * Beats, each stage generated by an agent, reviewed by a panel of parallel
 * Critics (see `CRITIC_ROLES` below), synthesized by an Arbitrator, and
 * gated on explicit human approval before advancing. This never writes
 * manuscript prose — that's still exclusively the Generate/Hanami flow;
 * this is the pre-writing/
 * planning phase, backed by the real backend's `agent_prompts` and
 * `planning_runs` tables (see the backend repo's
 * `src/routes/agentPrompts.ts` / `src/routes/planning.ts` and
 * `src/services/planningEngine.ts`).
 *
 * Every agent's behavior comes from a database row someone authors and
 * saves through the Prompt Editor — the backend contains zero prompt
 * content of its own. Every prompt this app's book currently has active
 * was written by an AI session getting the pipeline working end-to-end,
 * not the writer — see `AgentPromptAuthor` below for how the editor
 * surfaces that distinction.
 */

export type AgentRole =
  | "generator"
  | "continuity_critic"
  | "pacing_critic"
  | "craft_critic"
  | "arbitrator_panel"
  | "arbitrator_chat"
  | "arbitrator_directive"
  | "entity_extractor";

export const AGENT_ROLES: AgentRole[] = [
  "generator",
  "continuity_critic",
  "pacing_critic",
  "craft_critic",
  "arbitrator_panel",
  "arbitrator_chat",
  "arbitrator_directive",
  "entity_extractor",
];

/**
 * The critics making up the Scrutiny Panel, run in parallel by the
 * backend's `runCritique` — mirrors `CRITIC_ROLES` in the backend's own
 * `src/types/domain.ts`. Was `logic_critic`/`suspense_critic` (2); split
 * into 3 non-overlapping critics after a real case where pacing-specific
 * issues (chapter economy, cliffhanger cadence, decompression) went
 * uncaught because "emotional pacing" was buried as one bullet inside a
 * critic mostly focused on subtext/hooks. `logic_critic`/`suspense_critic`
 * are no longer valid `agentRole` values — `POST /agent-prompts` rejects
 * them with a 400. This list exists for display ordering/defaults only —
 * the actual Critique results panel (`ReviewGate` in planning/page.tsx)
 * renders one card per key actually present in a run's `panelReviews`,
 * not this fixed list, so the panel's composition can change again
 * without another frontend code change to the *display*, only to this
 * reference list and the Prompt Editor's selectable roles.
 */
export const CRITIC_ROLES: AgentRole[] = ["continuity_critic", "pacing_critic", "craft_critic"];

export const AGENT_ROLE_META: Record<AgentRole, { label: string; description: string }> = {
  generator: {
    label: "Generator",
    description: "Writes each stage's artifact — the Core Summary, Act Outlines, or Chapter Beats.",
  },
  continuity_critic: {
    label: "Continuity Critic",
    description: "Reviews the artifact for canon, timeline, and logic consistency (the old Logic Critic's scope).",
  },
  pacing_critic: {
    label: "Pacing & Chapter-Economy Critic",
    description: "Reviews chapter-to-plot ratio, decompression, cliffhanger cadence, and retention-curve pacing.",
  },
  craft_critic: {
    label: "Craft & Suspense Critic",
    description: "Reviews subtext, hook quality, anti-cliché, and foreshadowing/payoff (escalation/cadence moved to Pacing).",
  },
  arbitrator_panel: {
    label: "Arbitrator — Panel Synthesis",
    description: "Synthesizes both critics' reviews into one verdict for the human review gate.",
  },
  arbitrator_chat: {
    label: "Arbitrator — Chat",
    description: "Runs the interview after an artifact is rejected at the review gate.",
  },
  arbitrator_directive: {
    label: "Arbitrator — Directive",
    description: "Compiles the rejection interview into a delta directive for the next regeneration.",
  },
  entity_extractor: {
    label: "Entity Extractor",
    description: "Pulls new characters and world elements out of the approved Chapter Beats.",
  },
};

/**
 * `entity_extractor` is the one role that genuinely only ever needs a
 * single "all" version — the backend looks it up hardcoded at stage
 * `"all"` (see `extractEntities()` in the backend's `planningEngine.ts`),
 * never at a run's actual `current_stage`. A UI hint, not an enforced
 * rule elsewhere: "all" is always a valid stage for any role.
 */
export const SINGLE_STAGE_ROLES = new Set<AgentRole>(["entity_extractor"]);

/**
 * `arbitrator_chat` and `arbitrator_directive` are looked up at TWO
 * distinct stages depending on the moment: `"intake"` for the pre-Stage-1
 * conversation, and the run's real current stage (falling back to
 * `"all"`) for a mid-pipeline rejection interview — confirmed by reading
 * `intakeChatTurn()`/`finalizeIntake()` vs. `chatTurn()`/`finalizeDirective()`
 * in the backend directly. Each moment gets different placeholders (see
 * `placeholdersFor()` below), so these two roles need their own version
 * at `"intake"` AND one at `"all"` (or a specific stage) to work for both.
 */
export const DUAL_MOMENT_ROLES = new Set<AgentRole>(["arbitrator_chat", "arbitrator_directive"]);

export type PlanningStage = "stage_1_summary" | "stage_2_acts" | "stage_3_beats" | "intake" | "all";

export const PLANNING_STAGES: PlanningStage[] = ["stage_1_summary", "stage_2_acts", "stage_3_beats", "intake", "all"];

/** The three real pipeline stages, in order — a run's `current_stage` is never "all" or "intake"; those only exist as prompt-lookup stages. */
export const RUN_STAGES: Exclude<PlanningStage, "all" | "intake">[] = ["stage_1_summary", "stage_2_acts", "stage_3_beats"];

export const PLANNING_STAGE_META: Record<PlanningStage, { label: string; short: string }> = {
  stage_1_summary: { label: "Stage 1 — Core Summary", short: "Summary" },
  stage_2_acts: { label: "Stage 2 — Act Outlines", short: "Acts" },
  stage_3_beats: { label: "Stage 3 — Chapter Beats", short: "Beats" },
  intake: { label: "Intake (pre-Stage 1)", short: "Intake" },
  all: { label: "All Stages", short: "All" },
};

export const EFFORT_LEVELS = ["low", "medium", "high", "xhigh", "max"] as const;
export type EffortLevel = (typeof EFFORT_LEVELS)[number];

export const DEFAULT_MODEL = "claude-sonnet-5";
export const DEFAULT_EFFORT: EffortLevel = "high";

/**
 * Who wrote this version — `"claude"` for the prompts an AI session
 * seeded to get this book's pipeline working, `"writer"` for anything
 * the actual writer has authored or edited themselves. Not enforced by
 * any type on the backend's own side (its `agent_prompts` row shape
 * doesn't declare this field in TypeScript), but the column is real —
 * `GET /agent-prompts` returns it via a plain `select("*")`, and it's
 * absent-safe here (`mapPromptRow` falls back to `"writer"`) in case a
 * row genuinely doesn't have it set.
 */
export type AgentPromptAuthor = "writer" | "claude";

/** One authored version of one agent's behavior at one stage — every field is writer-owned, nothing here is generated. */
export type AgentPrompt = {
  id: string;
  bookId: string;
  agentRole: AgentRole;
  stage: PlanningStage;
  version: number;
  isActive: boolean;
  systemPrompt: string;
  userPromptTemplate: string;
  model: string;
  effort: EffortLevel;
  authoredBy: AgentPromptAuthor;
  createdAt: string;
};

export type PlanningRunStatus =
  | "intake_active"
  | "generating"
  | "critiquing"
  | "awaiting_arbitration"
  | "awaiting_user_review"
  | "user_chat_active"
  | "awaiting_entity_review"
  | "done"
  | "failed";

export const PLANNING_RUN_STATUS_LABEL: Record<PlanningRunStatus, string> = {
  intake_active: "Describing your book",
  generating: "Generating",
  critiquing: "Running critique",
  awaiting_arbitration: "Arbitrating",
  awaiting_user_review: "Awaiting your review",
  user_chat_active: "Rejection interview",
  awaiting_entity_review: "Reviewing extracted entities",
  done: "Done",
  failed: "Failed",
};

export type PlanningChatMessage = { role: "user" | "assistant"; content: string };

export type ExtractedEntityCandidate = {
  type: "codex_entry" | "world_category";
  name: string;
  entryType?: string;
  description?: string;
};

export type PlanningRun = {
  id: string;
  bookId: string;
  userId: string;
  currentStage: Exclude<PlanningStage, "all" | "intake">;
  status: PlanningRunStatus;
  stageArtifacts: Partial<Record<Exclude<PlanningStage, "all" | "intake">, string>>;
  /**
   * Keyed by critic role (see `CRITIC_ROLES`) — an open map, not a fixed
   * set of named fields, since the panel's composition isn't hardcoded on
   * either side. Each issue inside a critic's own `issues` array also
   * carries a `status: "new" | "unresolved" | "resolved"` field on a
   * revision pass (the critic marks its own prior issues resolved/
   * unresolved before looking for anything new) — rendered as a small
   * badge in the Critique display, see `ReviewGate`/`StructuredValue`.
   */
  panelReviews: Record<string, unknown> | null;
  arbitratorSynthesis: unknown;
  /** Mid-pipeline rejection interviews — a separate thread from intakeChatHistory. */
  chatHistory: PlanningChatMessage[];
  /** The one-time pre-Stage-1 conversation (status "intake_active") where the writer describes the book. */
  intakeChatHistory: PlanningChatMessage[];
  finalDeltaDirective: string | null;
  extractedEntities: ExtractedEntityCandidate[] | null;
  lastError: string | null;
  createdAt: string;
  updatedAt: string;
};

/**
 * Which `{{PLACEHOLDER}}` tokens a role's user_prompt_template can
 * reference — shown next to the template field in the Prompt Editor.
 * Anything not present in a given call is just left blank server-side,
 * no error, so this is documentation, not validation.
 *
 * A function, not a flat per-role table, because `arbitrator_chat` and
 * `arbitrator_directive` genuinely receive different placeholders
 * depending on *which* moment their prompt is being looked up for —
 * confirmed by reading `intakeChatTurn()`/`finalizeIntake()` (stage
 * `"intake"`) vs. `chatTurn()`/`finalizeDirective()` (any other stage)
 * directly in the backend's `planningEngine.ts`, rather than trusting a
 * single static table. `entity_extractor` also actually receives
 * `{{CURRENT_ARTIFACT}}` (the approved Stage 3 Beats JSON) even though
 * an earlier version of the feature spec omitted it — confirmed the same
 * way, via `extractEntities()`.
 */
export function placeholdersFor(role: AgentRole, stage: PlanningStage): { token: string; meaning: string }[] {
  switch (role) {
    case "generator":
      return [
        { token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" },
        { token: "{{PRIOR_STAGE_ARTIFACT}}", meaning: "The previous stage's approved text (blank at Stage 1)" },
        { token: "{{FINAL_DELTA_DIRECTIVE}}", meaning: "Set after intake, or after a rejection's finalize-directive" },
      ];
    case "continuity_critic":
    case "pacing_critic":
    case "craft_critic":
      return [
        { token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" },
        { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact currently being reviewed" },
        {
          token: "{{PREVIOUS_CRITIQUE}}",
          meaning: "This critic's own previous review of this same stage's artifact — empty on a first review, populated on a revision pass",
        },
      ];
    case "arbitrator_panel":
      return [
        { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact currently being reviewed" },
        { token: "{{PANEL_REVIEWS}}", meaning: "All critics' JSON output" },
        {
          token: "{{PREVIOUS_SYNTHESIS}}",
          meaning: "This Arbitrator's own previous synthesis of this same stage — empty on a first synthesis, populated on a revision pass",
        },
      ];
    case "arbitrator_chat":
      return stage === "intake"
        ? [
            {
              token: "{{BOOK_CONTEXT}}",
              meaning: "Book Facts + Codex JSON — keeps intake aware of an already-established book",
            },
          ]
        : [
            { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact being reconsidered after rejection" },
            { token: "{{PANEL_REVIEWS}}", meaning: "All critics' JSON output" },
          ];
    case "arbitrator_directive":
      return stage === "intake"
        ? [{ token: "{{CHAT_HISTORY}}", meaning: "The full intake conversation" }]
        : [
            { token: "{{CHAT_HISTORY}}", meaning: "The full rejection interview" },
            { token: "{{PANEL_REVIEWS}}", meaning: "All critics' JSON output" },
            { token: "{{CURRENT_ARTIFACT}}", meaning: "The artifact being reconsidered" },
          ];
    case "entity_extractor":
      return [
        { token: "{{BOOK_CONTEXT}}", meaning: "Book Facts + every current Codex entry, as JSON" },
        { token: "{{CURRENT_ARTIFACT}}", meaning: "The approved Stage 3 Chapter Beats JSON to extract entities from" },
      ];
    default:
      // A role the backend added that this file doesn't recognize yet (see
      // AGENT_ROLES' comment on the Prompt Editor's defensive fallback) —
      // no known placeholders to document rather than a crash.
      return [];
  }
}

/**
 * A readable label for any role string — `AGENT_ROLE_META`'s hand-written
 * label when we know it, otherwise a derived title-cased fallback (splits
 * both `snake_case` and `camelCase`) so a role the backend added or
 * renamed before this file caught up still shows something readable
 * instead of crashing or silently disappearing from the Prompt Editor's
 * Role dropdown or the Critique results display. Takes a plain `string`,
 * not `AgentRole`, on purpose — the whole point is to handle roles this
 * file's own type doesn't (yet) know about.
 */
export function roleLabel(role: string): string {
  const known = AGENT_ROLE_META[role as AgentRole];
  if (known) return known.label;
  return role
    .replace(/[_-]+/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/** A short note on which stage(s) a role is actually looked up at, for the roles where that isn't just "whatever you pick." */
export function roleStageGuidance(role: AgentRole): string | null {
  if (SINGLE_STAGE_ROLES.has(role)) {
    return 'Always looked up at stage "All Stages" — save your version there.';
  }
  if (DUAL_MOMENT_ROLES.has(role)) {
    return 'Looked up separately for two different moments: "Intake" for the pre-Stage-1 conversation, and the run\'s current stage (falling back to "All Stages") for a rejection interview. Save a version at each if you want them to sound different.';
  }
  return null;
}

/**
 * Two role/stage combinations get parsed by code, not just displayed —
 * getting the shape wrong means a clean, specific error rather than a
 * crash, but still worth a visible hint in the editor.
 */
export function outputShapeHint(role: AgentRole, stage: PlanningStage): string | null {
  if (role === "generator" && stage === "stage_3_beats") {
    return 'Must return JSON:\n{"chapters": [{"chapterNumber": 1, "title": "...", "beats": [{"title": "...", "outlineText": "..."}]}]}';
  }
  if (role === "entity_extractor") {
    return 'Must return a JSON array:\n[{"type": "codex_entry" | "world_category", "name": "...", "entryType": "...", "description": "..."}]';
  }
  return null;
}
